services:
  imc-front:
    image: simachille/imc-front:1.0.0
    container_name: imc-front
    restart: always
    networks:
      - applications-network

networks:
  applications-network:
    external: true
    name: applications-network
